# Generated by Django 4.0.2 on 2022-02-23 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirebaseUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("screen_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("picture", models.CharField(blank=True, default="", max_length=300)),
                ("is_stuff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
