# Generated by Django 4.0.1 on 2022-01-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.DeleteModel(
            name='RoutineEveryDay',
        ),
        migrations.DeleteModel(
            name='RoutineEveryWeek',
        ),
        migrations.DeleteModel(
            name='RoutineSpecDay',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
