# Generated by Django 4.0.2 on 2022-02-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_firebaseuser"),
        ("routine_api", "0005_alter_routineeveryweek_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routineeveryday",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_%(class)s",
                to="users.firebaseuser",
            ),
        ),
        migrations.AlterField(
            model_name="routineeveryweek",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_%(class)s",
                to="users.firebaseuser",
            ),
        ),
        migrations.AlterField(
            model_name="routinespecday",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_%(class)s",
                to="users.firebaseuser",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_routine_setting",
                to="users.firebaseuser",
            ),
        ),
    ]
